export const ROUTE_PATHS = {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    VERIFY_OTP: '/verify-otp',
    RESET_PASSWORD: '/reset-password',
    CHECK_EMAIL: '/check-email',
    SET_NEW_PASSWORD: '/set-new-password',
    DASHBOARD: '/dashboard',
    MOVIES: '/movies',
    MOVIE_DETAIL: '/movies/:id',
    GENRES: '/genres',
    DIRECTORS: '/directors',
    STARS: '/stars',
    SCHEDULES: '/schedules',
    SCHEDULE_DETAIL: '/schedules/:id',
    TICKETS: '/tickets',
    TICKET_DETAIL: '/tickets/:id',
    SETTINGS: '/settings',
};
